[tool.poetry]
name = "covi19"
version = "0.1.0"
description = ""
authors = ["AlexSJ33 <alevildark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyQt5 = "^5.15.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
